version: "3.3"
services:
  nginx:
    container_name: reverse-proxy
    image: ubuntu/nginx:1.18-22.04_beta
    restart: always
    volumes:
      - $PWD/html:/var/www/html
      - $PWD/conf/ngnix.conf:/etc/nginx/nginx.conf
      - $PWD/conf/default.conf:/etc/nginx/sites-available/default
      - $PWD/conf/mime.types:/etc/nginx/mime.types
      - $PWD/logs:/var/log/nginx
      - $PWD/ssl:/etc/ssl
    environment:
      - TZ:UTC-4
    ports:
      - "80:80"
      - "443:443"
