services:
    logia-server:
      container_name: logia-server
      image: logia:prd
      build: .
      restart: always
      volumes:
        - ./app:/home/logia/app
      ports:
        - "58085:58085"
      env_file:
      - ../../envs/logia.env
      networks:
        - db-net
      # command: tail -f /home/logia/requirements.txt
networks:
  db-net:
