version: "3.3"
services:
    logia-server:
      container_name: logia-server
      build: .
      restart: always
      volumes:
        - ./app:/home/logia/app
      ports:
        - "58085:58085"
      env_file:
      - env.prod
      networks:
        - db-net
      # command: tail -f /home/logia/requirements.txt
networks:
  db-net:
